/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e4e2e0",
        "surface-dim": "#dbdad7",
        "surface-container": "#f0edeb",
        background: "#fbf9f7",
        "primary-container": "#3e4c41",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#2f1500",
        "surface-bright": "#fbf9f7",
        "on-error": "#ffffff",
        secondary: "#695c4f",
        "secondary-fixed-dim": "#d5c4b4",
        "on-secondary-fixed": "#231a10",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#504539",
        outline: "#747873",
        "on-primary-fixed": "#111e15",
        "inverse-on-surface": "#f2f0ee",
        "inverse-surface": "#30302f",
        "on-tertiary-container": "#ffa352",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-container-highest": "#e4e2e0",
        "on-primary-fixed-variant": "#3c4a3f",
        "on-error-container": "#93000a",
        "on-secondary-container": "#6d6053",
        "secondary-container": "#efddcc",
        "on-surface": "#1b1c1b",
        "surface-container-high": "#eae8e6",
        "on-primary-container": "#acbcae",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-container-low": "#f5f3f1",
        "on-background": "#1b1c1b",
        primary: "#28352b",
        "outline-variant": "#c3c8c1",
        "on-surface-variant": "#434843",
        "primary-fixed-dim": "#bbcbbc",
        "tertiary-fixed": "#ffdcc3",
        "surface-tint": "#536256",
        "tertiary-container": "#713b00",
        surface: "#fbf9f7",
        "on-tertiary": "#ffffff",
        tertiary: "#502800",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d7e7d8",
        "secondary-fixed": "#f1dfcf",
        "inverse-primary": "#bbcbbc",
        "on-tertiary-fixed-variant": "#6e3900",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "element-gap": "24px",
        "grid-gutter": "24px",
        "section-gap": "80px",
        base: "8px",
        "container-padding": "40px",
        "grid-columns": "12",
      },
      fontFamily: {
        "headline-lg": ["Noto Serif", "serif"],
        "data-display": ["Inter", "sans-serif"],
        "headline-md": ["Noto Serif", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Noto Serif", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        serif: ["Noto Serif", "serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "data-display": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      boxShadow: {
        glow: "0 0 40px rgba(40, 53, 43, 0.15)",
        "glow-lg": "0 0 80px rgba(40, 53, 43, 0.2)",
      },
      backgroundImage: {
        "hero-mesh":
          "linear-gradient(135deg, rgba(40,53,43,0.08) 0%, rgba(105,92,79,0.06) 50%, rgba(40,53,43,0.04) 100%)",
      },
      animation: {
        "scan-line": "scan-line 4s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
      },
    },
  },
  plugins: [],
};
