import { Card, CardContent, CardHeader, CardTitle } from "../core/Card";
import { AlertTriangle, CheckCircle, Info } from "lucide-react";

interface RiskAssessmentProps {
  riskLevel: "LOW" | "MODERATE" | "HIGH" | "CRITICAL";
  confidence: number;
  summary?: string;
  disclaimer?: string;
}

export function RiskAssessmentWidget({
  riskLevel,
  confidence,
  summary,
  disclaimer,
}: RiskAssessmentProps) {
  const disclaimerText =
    disclaimer?.trim() ||
    "This assessment is a preliminary triage output generated by an AI model. It does not constitute a definitive medical diagnosis. If you are concerned about this result, please consult a licensed dermatologist.";

  const getRiskColor = () => {
    switch (riskLevel) {
      case "CRITICAL":
        return "text-red-300 bg-red-500/10 border-red-500/20";
      case "HIGH":
        return "text-orange-300 bg-orange-500/10 border-orange-500/20";
      case "MODERATE":
        return "text-amber-300 bg-amber-500/10 border-amber-500/20";
      case "LOW":
        return "text-emerald-300 bg-emerald-500/10 border-emerald-500/20";
    }
  };

  const getRiskIcon = () => {
    switch (riskLevel) {
      case "CRITICAL":
        return <AlertTriangle className="h-10 w-10 text-red-400 mb-3" />;
      case "HIGH":
        return <AlertTriangle className="h-10 w-10 text-orange-400 mb-3" />;
      case "MODERATE":
        return <Info className="h-10 w-10 text-amber-400 mb-3" />;
      case "LOW":
        return <CheckCircle className="h-10 w-10 text-emerald-400 mb-3" />;
    }
  };

  return (
    <Card className="w-full glass border-white/5">
      <CardHeader className="glass-light border-b border-white/5 rounded-t-xl">
        <CardTitle className="text-white">Automated Risk Assessment</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6 pt-6">
        <div
          className={`p-8 rounded-xl border flex flex-col items-center justify-center text-center ${getRiskColor()}`}
        >
          {getRiskIcon()}
          <h2 className="text-3xl font-bold mb-1 tracking-tight">
            {riskLevel} RISK DETECTED
          </h2>
          <p className="text-sm opacity-80 font-medium">
            AI Triage Confidence: {confidence}%
          </p>
        </div>

        {summary && (
          <div className="glass-light p-5 rounded-lg text-sm text-slate-300 whitespace-pre-line">
            <p className="font-semibold mb-2 text-white">AI Summary</p>
            <p>{summary}</p>
          </div>
        )}

        <div className="glass-light p-5 rounded-lg text-sm text-slate-400">
          <p className="font-semibold mb-2 text-slate-300">
            Clinical Disclaimer
          </p>
          <p>{disclaimerText}</p>
        </div>
      </CardContent>
    </Card>
  );
}
